Changed fileupload library from org.apache.tomcat.util.http.fileupload to org.apache.commons.fileupload because of a NoSuchMethodError on ServletFileUpload.parseRequest(...) on the Tomcat Server on the ETH machine.